### ISSUE TITLE
Features & Improvements

### ISSUE THREAD

**Issue by realgooseman** [ErenCanUtku/MyNotes#4]
Hi @Erencrypt,

Great little app. Well done.
I have some features and improvements I would like to suggest, let me know what you think.

### **Visibility**
First of all, the app was quite hard to find so I would suggest submitting the app on [AlternativeTo](https://alternativeto.net/) to gain visibility and popularize the app among the FOSS community.

### **Localization**
Currently the app is only available in English, I've seen that you work on the code to implement localization. Setting up a [**Crowdin**](https://crowdin.com/) panel to get easier translation contributions might be a good idea. I could personally contribute in French and Dutch.

### **UI redesign**
Design taste is subjective. However, inspiring yourself from other apps/services might help in bringing new users as they are already familiar with such interfaces. Great design ideas might be [**Google Keep**](https://alternativeto.net/software/google-keep/about/) and open-source Android app called [**Noto**](https://github.com/alialbaali/Noto) which have very clean and simple interfaces with bubble-like note boxes.

### **New feature : To-do checklist**
Your app already has an advantage over the other proprietary "simple" note apps. It got reminders and text formatting. Merging the in-app reminder with a simple to-do checklist feature on the sidebar would make it a multi-usage yet simple app. Something similar to what [**Microsoft To-Do**](https://apps.microsoft.com/detail/9NBLGGH5R558) looks like. With task name, task description, reminder, deadline, repeat task with daily/weekly/monthly/custom intervals...

**Comment by Erencrypt** [comment]
@realgooseman I'm currently working on some problems (or we can call them needed improvements to code) that I want to solve with app.
- **About checklist feature:** I was thinking about similar feature, but you described it better than what I have in my mind, I will try to add that.
- Also, I will try to apply your suggestions about visibility and localization when app is ready (as I mentioned before, currently app needs some improvements).
I wrote this app as I learn winUI, so there is a lot to improve and suggestions are important for me. Thank you, I really appreciate it.
